name: Deploy to Cloudron

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: front-staging
    
    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Deploy to Cloudron
      - name: Cloudron Push to App
        uses: cloudron-io/cloudron-push-to-app@latest
        with:
          # Cloudron instance FQDN
          CLOUDRON_FQDN: "${{ secrets.CLOUDRON_FQDN }}"
          # Cloudron API token with read-write permissions
          CLOUDRON_TOKEN: "${{ secrets.CLOUDRON_TOKEN }}"
          # Application ID in Cloudron
          CLOUDRON_APP_ID: "${{ secrets.CLOUDRON_APP_ID }}"
          # Destination path in the Cloudron app for deployment
          CLOUDRON_PUSH_DESTINATION: "/app/data"
          # Create a backup before deploying
          CLOUDRON_CREATE_APP_BACKUP: "false"
